name: update chart versions

on:
  repository_dispatch:
    types: tag-released

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      # REMOTE_REF: ${{ github.event.client_payload.ref }}
      REMOTE_REF: 2.3.0

    steps:

    - name: prepare environment
      run: |
        if [[ ${REMOTE_REF} =~ ^([0-9]+\.)?([0-9]+\.)?(\*|[0-9]+)$ ]]; then
          echo "tag is valid: $REMOTE_REF"
          echo "CONTINUE=true" >> $GITHUB_ENV
        else
          echo "could not validate tag: $REMOTE_REF"
        fi

    - name: checkout commit
      if: env.CONTINUE
      uses: actions/checkout@v3
      with:
        token: ${{secrets.HELMREPO_ACCESS_TOKEN}}
        fetch-depth: 0

    - name: update versions
      if: env.CONTINUE
      run: |
        sed -i "s/version:.*/version: ${{ env.REMOTE_REF }}/" "charts/inscriptis/Chart.yaml"
        sed -i "s/appVersion:.*/appVersion: ${{ env.REMOTE_REF }}/" "charts/inscriptis/Chart.yaml"
        sed -i "s/  tag:.*/  tag: ${{ env.REMOTE_REF }}/" "charts/inscriptis/values.yaml"

    - name: push version commit
      if: env.CONTINUE
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add -A
        git commit -m '[github-actions] bump chart version number.'
        git push
