name: update chart versions

on:
  repository_dispatch:
    types: tag-released

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:

    - name: prepare environment
      with:
        _remote_ref: ${{ github.event.client_payload.ref }}
      run: |
        if [[ $_remote_ref =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$ ]]; then
          echo "tag is valid: $_remote_ref."
          echo "REMOTE_REF=$_remote_ref" >> $GITHUB_ENV
        else
          echo "could not validate tag: $_remote_ref."
          echo "EARLY_EXIT=true" >> $GITHUB_ENV
        fi

    - name: checkout commit
      if: ${{ env.EARLY_EXIT != true }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: update versions
      if: ${{ env.EARLY_EXIT != true }}
      run: |
        sed -i "s/version:.*/version: ${{ env.REMOTE_REF }}/" "charts/inscriptis/Chart.yaml"
        sed -i "s/appVersion:.*/appVersion: ${{ env.REMOTE_REF }}/" "charts/inscriptis/Chart.yaml"
        sed -i "s/  tag:.*/  tag: ${{ env.REMOTE_REF }}/" "charts/inscriptis/values.yaml"

    - name: push version commit
      if: ${{ env.EARLY_EXIT != true }}
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add -A
        git commit -m '[github-actions] bump chart version number.'
        git push